import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getDocuments } from "@/lib/doc";
import Header from "./Components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Docucrapt",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

 const allDocuments = getDocuments();
 console.log(allDocuments)

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
       <div className="bg-white text-black min-h-screen">

          <div>
            <Header></Header>
          </div>

           {children}
       </div>
      </body>
    </html>
  );
}
